
let tempBox= document.querySelector(".temprature");
let cityBox= document.querySelector(".city");
let weatherBox= document.querySelector(".weather");
let windbox = document.querySelector(".wind");
let nextDay = document.querySelector("#forecast1");
let nextDay2 = document.querySelector("#forecast2");
let nextDay3 = document.querySelector("#forecast3");
let cityDropDown = document.querySelector(".countries");
let flags = document.querySelector(".flgImg");

const cityCountryCode = {
    "London": "GB",
    "Newyork": "US",
    "Chicago": "US",
    "Seattle": "US",
    "Houston": "US",
    "Philadelphia": "US",
    "San Diego": "US",
    "Dubai": "AE",
    "Beijing": "CN",
    "Tokyo": "JP",
    "Delhi": "IN",
    "Paris": "FR",
    "Mumbai": "IN",
    "Karachi": "PK",
    "Islamabad": "PK",
    "Lahore": "PK",
    "Agra": "IN",
    "Barcelona": "ES",
    "Bangkok": "TH", // corrected "Bankok" to "Bangkok"
    "Amsterdam": "NL",
    "Berlin": "DE",
    "Cairo": "EG",
    "Kolkata": "IN", // assuming you meant "Kolkata"
    "Dhaka": "BD",
    "Jeddah": "SA",
    "Moscow": "RU",
    "Tehran": "IR",
    "Baghdad": "IQ",
    "Singapore": "SG",
    "Madrid": "ES",
    "Faisalabad": "PK",
    "Beijing": "CN",
    "Sydney": "AU",
    "Rio de Janeiro": "BR",
    "Los Angeles": "US",
    "San Francisco": "US",
    "Rome": "IT",
    "Venice": "IT",
    "Athens": "GR",
    "Istanbul": "TR",
    "Vienna": "AT",
    "Zurich": "CH",
    "Hong Kong": "HK",
    "Dubai": "AE",
    "Toronto": "CA",
    "Vancouver": "CA",
    "Melbourne": "AU",
    "Cape Town": "ZA",
    "Buenos Aires": "AR",
    "Sao Paulo": "BR",
    "Mexico City": "MX",
    "Lima": "PE",
    "Santiago": "CL",
    "Prague": "CZ",
    "Warsaw": "PL",
    "Budapest": "HU",
    "Copenhagen": "DK",
    "Stockholm": "SE",
    "Helsinki": "FI",
    "Oslo": "NO",
    "Lisbon": "PT",
    "Brussels": "BE",
    "Munich": "DE",
    "Frankfurt": "DE",
    "Geneva": "CH",
    "Milan": "IT",
    "Florence": "IT",
    "Naples": "IT",
    "Bucharest": "RO",
    "Belgrade": "RS",
    "Sofia": "BG",
    "Zagreb": "HR",
    "Ljubljana": "SI",
    "Bratislava": "SK",
    "Tallinn": "EE",
    "Riga": "LV",
   "Sydney": "AU",
    "Melbourne": "AU",
    "Toronto": "CA",
    "Vancouver": "CA",
    "Montreal": "CA",
    "Buenos Aires": "AR",
    "Sao Paulo": "BR",
    "Rio de Janeiro": "BR",
    "Lima": "PE",
    "Bogota": "CO",
    "Santiago": "CL",
    "Brasilia": "BR",
    "Caracas": "VE",
    "Montevideo": "UY",
    "Quito": "EC",
    "Asuncion": "PY",
    "La Paz": "BO",
    "Havana": "CU",
    "Panama City": "PA",
    "San Jose": "CR",
    "San Salvador": "SV",
    "Guatemala City": "GT",
    "Tegucigalpa": "HN",
    "Managua": "NI",
    "Kingston": "JM",
    "Nassau": "BS",
    "Port-au-Prince": "HT",
    "Santo Domingo": "DO",
    "Port of Spain": "TT",
    "Castries": "LC",
    "Bridgetown": "BB",
    "Roseau": "DM",
    "Kingstown": "VC",
    "Saint John's": "AG",
    "Basseterre": "KN",
    "Georgetown": "GY",
    "Paramaribo": "SR",
    "Cayenne": "GF",
    "Reykjavik": "IS",
    "Helsinki": "FI",
    "Oslo": "NO",
    "Stockholm": "SE",
    "Copenhagen": "DK",
    "Amsterdam": "NL",
    "Brussels": "BE",
    "Luxembourg": "LU",
    "Berlin": "DE",
    "Vienna": "AT",
    "Bern": "CH",
    "Warsaw": "PL",
    "Prague": "CZ",
    "Bratislava": "SK",
    "Budapest": "HU",
    "Ljubljana": "SI",
    "Zagreb": "HR",
    "Sarajevo": "BA",
    "Belgrade": "RS",
    "Podgorica": "ME",
    "Tirana": "AL",
    "Skopje": "MK",
    "Sofia": "BG",
    "Bucharest": "RO",
    "Chisinau": "MD",
    "Kiev": "UA",
    "Minsk": "BY",
    "Vilnius": "LT",
    "Riga": "LV",
    "Tallinn": "EE",
    "Moscow": "RU",
    "Saint Petersburg": "RU",
    "Baku": "AZ",
    "Yerevan": "AM",
    "Tbilisi": "GE",
    "Nur-Sultan": "KZ",
    "Tashkent": "UZ",
    "Bishkek": "KG",
    "Dushanbe": "TJ",
    "Ashgabat": "TM",
    "Ulaanbaatar": "MN",
    "Beijing": "CN",
    "Shanghai": "CN",
    "Hong Kong": "HK",
    "Macau": "MO",
    "Taipei": "TW",
    "Seoul": "KR",
    "Tokyo": "JP",
    "Osaka": "JP",
    "Kyoto": "JP",
    "Manila": "PH",
    "Bangkok": "TH",
    "Hanoi": "VN",
    "Ho Chi Minh City": "VN",
    "Phnom Penh": "KH",
    "Vientiane": "LA",
    "Yangon": "MM",
    "Kuala Lumpur": "MY",
    "Singapore": "SG",
    "Jakarta": "ID",
    "Bandar Seri Begawan": "BN",
    "Islamabad": "PK",
    "Karachi": "PK",
    "Lahore": "PK",
    "Dhaka": "BD",
    "Kathmandu": "NP",
    "Thimphu": "BT",
    "Male": "MV",
    "Colombo": "LK",
    "New Delhi": "IN",
    "Mumbai": "IN",
    "Bangalore": "IN",
    "Chennai": "IN",
    "Hyderabad": "IN",
    "Kolkata": "IN",
    "Ahmedabad": "IN",
    "Pune": "IN",
    "Surat": "IN",
    "Jaipur": "IN",
    "Lucknow": "IN",
    "Kanpur": "IN",
    "Nagpur": "IN",
    "Indore": "IN",
    "Thane": "IN",
    "Bhopal": "IN",
    "Visakhapatnam": "IN",
    "Pimpri-Chinchwad": "IN",
    "Patna": "IN",
    "Vadodara": "IN",
    "Ghaziabad": "IN",
    "Ludhiana": "IN",
    "Agra": "IN",
    "Nashik": "IN",
    "Faridabad": "IN",
    "Meerut": "IN",
    "Rajkot": "IN",
    "Kalyan-Dombivli": "IN",
    "Vasai-Virar": "IN",
    "Varanasi": "IN",
    "Srinagar": "IN",
    "Aurangabad": "IN",
    "Dhanbad": "IN",
    "Amritsar": "IN",
    "Navi Mumbai": "IN",
    "Allahabad": "IN",
    "Howrah": "IN",
    "Ranchi": "IN",
    "Coimbatore": "IN",
    "Jabalpur": "IN",
    "Gwalior": "IN",
    "Vijayawada": "IN",
    "Jodhpur": "IN",
    "Madurai": "IN",
    "Raipur": "IN",
    "Kota": "IN",
    "Guwahati": "IN",
    "Chandigarh": "IN",
    "Solapur": "IN",
    "Hubli-Dharwad": "IN",
    "Mysore": "IN",
    "Tiruchirappalli": "IN",
    "Bareilly": "IN",
    "Aligarh": "IN",
    "Tiruppur": "IN",
    "Gurgaon": "IN",
    "Moradabad": "IN",
    "Jalandhar": "IN",
    "Bhubaneswar": "IN",
    "Salem": "IN",
    "Warangal": "IN",
    "Mira-Bhayandar": "IN",
    "Thiruvananthapuram": "IN",
    "Bhiwandi": "IN",
    "Saharanpur": "IN",
    "Guntur": "IN",
    "Amravati": "IN",
    "Bikaner": "IN",
    "Noida": "IN",
    "Jamshedpur": "IN",
    "Bhilai": "IN",
    "Cuttack": "IN",
    "Kochi": "IN",
    "Udaipur": "IN",
    "Bhavnagar": "IN",
    "Dehradun": "IN",
    "Asansol": "IN",
    "Nanded": "IN",
    "Ajmer": "IN",
    "Jamnagar": "IN",
    "Ujjain": "IN",
    "Sangli": "IN",
    "Loni": "IN",
    "Jhansi": "IN",
    "Pondicherry": "IN",
    "Nellore": "IN",
    "Jammu": "IN",
    "Belgaum": "IN",
    "Raurkela": "IN",
    "Mangalore": "IN",
    "Tirunelveli": "IN",
    "Malegaon": "IN",
    "Gaya": "IN",
    "Tirupati": "IN",
    "Uzhhorod": "UA",
    "Ivano-Frankivsk": "UA",
    "Bila Tserkva": "UA",
    "Kamianets-Podilskyi": "UA",
    "Melitopol": "UA",
    "Sloviansk": "UA",
    "Uman": "UA",
    "Kremenchuk": "UA",
    "Berdyansk": "UA",
    "Kropyvnytskyi": "UA",
    "Sevastopol": "UA",
    "Kerch": "UA",
    "Yalta": "UA",
    "Simferopol": "UA",
    "Dnipro": "UA",
    "Odesa": "UA",
    "Kherson": "UA",
    "Kharkiv": "UA",
    "Zaporizhzhia": "UA",
    "Vinnytsia": "UA",
    "Mykolaiv": "UA",
    "Chernihiv": "UA",
    "Cherkasy": "UA",
    "Zhytomyr": "UA",
    "Sumy": "UA",
    "Rivne": "UA",
    "Ternopil": "UA",
    "Lutsk": "UA",
    "Chernivtsi": "UA",
    "Mukachevo": "UA",
    "Khmelnytskyi": "UA",
    "Luhansk": "UA",
    "Donetsk": "UA",
    "Mariupol": "UA",
    "Kryvyi Rih": "UA",
    "Kramatorsk": "UA",
    "Horlivka": "UA",
    "Makiivka": "UA",
    "Brovary": "UA",
    "Boryspil": "UA",
    "Lviv": "UA",
    "Kyiv": "UA",
    "Poltava": "UA"

}
async function getWeather(city){
    const URL=("https://goweather.herokuapp.com/weather/"+city);  
    try{
    console.log("getting weather update.........")
     const response = await fetch(URL);
     const data = await response.json();
     console.log(data);
     tempBox.innerHTML=data.temperature;
     weatherBox.innerHTML=data.description;
     windbox.innerHTML=data.wind;
     cityBox.innerHTML=city;

     const boxes = [nextDay, nextDay2,  nextDay3];
     const forecastArray = data.forecast;
     for (let i = 0; i < forecastArray.length; i++) {
        const box = boxes[i];
        box.innerHTML = " ";

        const dayBoxElement = document.createElement("div");
        dayBoxElement.classList.add("nextdataBoxTitle");
        dayBoxElement.innerHTML = `Day: ${forecastArray[i].day}`;
        
        const tempElement = document.createElement("div");
        tempElement.classList.add("tempratureNextday");
        tempElement.innerHTML = forecastArray[i].temperature;

        const windElement = document.createElement("div");
        windElement.classList.add("windNextday");
        windElement.innerHTML = forecastArray[i].wind;

            box.appendChild(dayBoxElement);
           box.appendChild(tempElement);  
           box.appendChild(windElement);   
                         }
     const countryCode= cityCountryCode[city];
     console.log("code for " + city + " is " + countryCode);

     const flagURL= "https://flagsapi.com/"+ countryCode +"/shiny/64.png";
     flags.src=flagURL;
     console.log(countryCode);
     console.log(city);
    }
     catch(error){
          console.error("Error Fetching Weather Data: ", error);
                 }
    };

    cityDropDown.addEventListener("change",(event)=>{
        const selectedCity = event.target.value;
        getWeather(selectedCity);
    })
    getWeather(cityDropDown.value);